<?php
/**
 * Created by PhpStorm.
 * User: viktor
 * Date: 27.09.18
 * Time: 19:33
 */

namespace core\system\models;


use core\base\Model;
use core\system\hasher\PassHasher;

class User extends Model
{

    public function __set($name, $value)
    {
        //Если пользователь меняет пароль, хешируем его
        if($name === 'pass') $value = PassHasher::instance()->hash($value);
        parent::__set($name, $value); // TODO: Change the autogenerated stub
    }

}